export { default as Header } from "./Header"
export { default as JobExperiences } from "./JobExperiences"
export { default as Projects } from "./Projects"
export { default as CTA } from "./CTA"
export { default as Footer } from "./Footer"
